/**
 * WhatsItGot — Supplemental descriptions for technologies missing them in Wappalyzer.
 * Hand-curated one-line descriptions for well-known technologies.
 */
var WIG_DESCRIPTIONS = {
  "A-Frame": "Open-source web framework for building 3D and VR experiences in the browser.",
  "Adobe ColdFusion": "Commercial rapid web application development platform from Adobe, using CFML scripting.",
  "AdonisJS": "Full-featured Node.js web framework modeled after Laravel, with built-in ORM and auth.",
  "Alpine.js": "Lightweight JavaScript framework for composing behavior directly in HTML markup.",
  "Amazon ECS": "Amazon Elastic Container Service, a managed container orchestration platform on AWS.",
  "Atlassian Jira": "Issue tracking and project management tool widely used in agile software development.",
  "AWStats": "Open-source web analytics tool that generates statistics from server access logs.",
  "Blazor": "Microsoft framework for building interactive web UIs using C# instead of JavaScript.",
  "Bokeh": "Python library for creating interactive data visualizations for the web.",
  "Bolt CMS": "Lightweight open-source CMS built on PHP with Symfony components.",
  "Bunny": "Bunny.net is a global CDN and edge platform for fast, reliable content delivery.",
  "Caddy": "Open-source web server with automatic HTTPS, written in Go.",
  "Chartbeat": "Real-time content analytics platform for publishers and media companies.",
  "Cherokee": "Open-source cross-platform web server with a user-friendly admin interface.",
  "Clipboard.js": "Lightweight JavaScript library for copying text to the clipboard without Flash.",
  "CodeIgniter": "Lightweight PHP web framework known for its small footprint and speed.",
  "Concrete CMS": "Open-source CMS with in-context editing, formerly known as concrete5.",
  "CouchDB": "Apache NoSQL document database using JSON, JavaScript, and HTTP.",
  "Countly": "Open-source product analytics and engagement platform for mobile and web.",
  "Crazy Egg": "Website heatmap and A/B testing tool for understanding user behavior.",
  "DNN": "Open-source web CMS built on ASP.NET, formerly DotNetNuke.",
  "Daphne": "HTTP, HTTP2, and WebSocket server for Django ASGI applications.",
  "Day.js": "Lightweight JavaScript date library, a drop-in replacement for Moment.js at 2KB.",
  "Dojo": "JavaScript toolkit for building web applications with widgets, utilities, and data stores.",
  "Dropbox": "Cloud file storage and sharing service, detected via embedded widgets or API usage.",
  "Ember.js": "Opinionated JavaScript framework for building ambitious single-page web applications.",
  "ExtJS": "Commercial JavaScript framework for building data-intensive cross-platform web apps.",
  "Fat-Free Framework": "Lightweight PHP micro-framework with a powerful routing engine.",
  "Flat UI": "Free UI toolkit built on Bootstrap for creating flat-design web interfaces.",
  "FluxBB": "Fast, lightweight PHP forum software with minimal resource requirements.",
  "Flywheel": "Managed WordPress hosting platform designed for designers and agencies.",
  "GlassFish": "Open-source Java EE application server, the reference implementation for Jakarta EE.",
  "Go": "Google's compiled programming language, known for concurrency and fast performance.",
  "GoJS": "Commercial JavaScript library for building interactive diagrams and graphs.",
  "Google App Engine": "Google's fully managed serverless platform for building web applications.",
  "Google Code Prettify": "JavaScript library for syntax highlighting of source code in web pages.",
  "Google Sites": "Google's simple website builder included with Google Workspace.",
  "Google Wallet": "Google's digital wallet for online and in-store payments.",
  "Google Web Server": "Google's proprietary web server used to serve many Google properties.",
  "Grav": "Modern flat-file CMS built on PHP, requiring no database.",
  "Gravity Forms": "Popular premium WordPress plugin for building advanced forms.",
  "HHVM": "HipHop Virtual Machine, Facebook's JIT-compiling runtime for PHP and Hack.",
  "Halo": "Modern open-source Java-based CMS and blogging platform.",
  "Hammer.js": "JavaScript library for multi-touch gesture recognition on mobile and desktop.",
  "Haskell": "Purely functional programming language, detected when used for web backends.",
  "Highlight.js": "JavaScript library for syntax highlighting in the browser, supporting 190+ languages.",
  "Hogan.js": "JavaScript templating engine developed at Twitter, compiling Mustache templates.",
  "Hypercorn": "ASGI web server supporting HTTP/1, HTTP/2, and WebSockets for Python apps.",
  "Immutable.js": "Facebook's library providing immutable persistent data structures for JavaScript.",
  "Inspectlet": "Session recording and heatmap tool for understanding website visitor behavior.",
  "JBoss Application Server": "Open-source Java EE application server, now known as WildFly.",
  "Java Servlet": "Server-side Java technology for handling HTTP requests in web applications.",
  "JavaServer Faces": "Java web framework for building component-based user interfaces.",
  "JavaServer Pages": "Server-side Java technology for creating dynamic HTML content.",
  "Jetty": "Lightweight open-source Java HTTP server and servlet container from Eclipse.",
  "K2": "Content extension for Joomla CMS, adding blogging and catalog features.",
  "KISSmetrics": "Behavioral analytics and engagement platform for tracking customer journeys.",
  "Kajabi": "All-in-one platform for selling online courses, memberships, and digital products.",
  "Kestrel": "Cross-platform web server for ASP.NET Core, Microsoft's default web server.",
  "Kinsta": "Premium managed WordPress hosting powered by Google Cloud Platform.",
  "Koa": "Expressive Node.js web framework designed by the team behind Express.",
  "Kohana": "PHP web framework, a fork of CodeIgniter focused on strict OOP.",
  "Kubernetes Dashboard": "Web-based UI for managing and troubleshooting Kubernetes clusters.",
  "Less": "CSS preprocessor adding variables, mixins, and functions to stylesheets.",
  "Loom": "Video messaging and screen recording platform for async communication.",
  "Mambo": "Open-source PHP/MySQL CMS, the predecessor to Joomla.",
  "Marked": "Fast JavaScript Markdown parser and compiler for the browser and Node.js.",
  "Mattermost": "Open-source self-hosted messaging platform, an alternative to Slack.",
  "Mermaid": "JavaScript library for generating diagrams and charts from text definitions.",
  "Meteor": "Full-stack JavaScript platform for building real-time web and mobile applications.",
  "Milligram": "Minimalist CSS framework at just 2KB gzipped.",
  "MobX": "Simple, scalable state management library for JavaScript applications.",
  "Mojolicious": "Real-time web framework for the Perl programming language.",
  "MooTools": "Compact modular JavaScript framework for building cross-browser web applications.",
  "Movable Type": "Web publishing platform and CMS for enterprise and professional use.",
  "Neos CMS": "Open-source PHP CMS with inline editing, built on the Neos Flow framework.",
  "Neos Flow": "PHP application framework powering Neos CMS, following domain-driven design.",
  "NetSuite": "Oracle's cloud-based ERP, CRM, and ecommerce platform for businesses.",
  "Nette Framework": "PHP web framework focused on security, simplicity, and modern practices.",
  "PDF.js": "Mozilla's JavaScript library for rendering PDF files in the browser.",
  "Pagely": "Enterprise managed WordPress hosting platform on AWS.",
  "Pelican": "Static site generator written in Python, supporting Markdown and reStructuredText.",
  "Phaser": "Open-source HTML5 game framework for building 2D browser games.",
  "Phoenix": "Productive web framework for Elixir, known for real-time features and performance.",
  "Platform.sh": "Platform-as-a-service for building, deploying, and scaling web applications.",
  "Play": "Reactive web framework for Java and Scala with a developer-friendly workflow.",
  "Plotly": "JavaScript graphing library for creating interactive, publication-quality charts.",
  "Polymer": "Google's library for building web applications using Web Components.",
  "Pygments": "Python syntax highlighting library used in many documentation tools.",
  "PyroCMS": "PHP CMS built on Laravel with a modular addon system.",
  "Ramda": "Functional utility library for JavaScript, emphasizing immutability and pure functions.",
  "Reddit": "Social news aggregation platform, detected via embedded widgets.",
  "Redis Object Cache": "WordPress plugin using Redis for persistent object caching.",
  "Reveal.js": "Open-source HTML presentation framework for creating web-based slide decks.",
  "Riot": "Simple and elegant component-based JavaScript UI library.",
  "Rollbar": "Real-time error tracking and monitoring platform for web applications.",
  "SAP": "Enterprise software platform for business operations and customer relations.",
  "SQLite": "Self-contained serverless SQL database engine, the most widely deployed database.",
  "Sails.js": "MVC web framework for Node.js, inspired by Ruby on Rails.",
  "Sapper": "Web application framework powered by Svelte, predecessor to SvelteKit.",
  "Shiny": "R framework for building interactive web applications directly from R code.",
  "Slick": "Responsive carousel/slider jQuery plugin for building content sliders.",
  "Snap.svg": "JavaScript library for working with SVG graphics, the successor to Raphael.",
  "Socket.io": "JavaScript library enabling real-time, bidirectional communication via WebSockets.",
  "Spree": "Open-source headless ecommerce framework built on Ruby on Rails.",
  "Spring": "Comprehensive Java application framework widely used for enterprise web development.",
  "Statcounter": "Free web analytics service providing real-time visitor tracking.",
  "Strikingly": "Website builder focused on creating single-page websites quickly.",
  "SyntaxHighlighter": "JavaScript library for displaying formatted source code on web pages.",
  "TikTok Pixel": "TikTok's tracking pixel for measuring ad performance and conversions.",
  "TornadoServer": "Python web framework and asynchronous networking library for long-polling and WebSockets.",
  "Trac": "Open-source wiki and issue tracking system for software development projects.",
  "Uvicorn": "Lightning-fast ASGI server for Python, commonly used with FastAPI and Starlette.",
  "Vercel Analytics": "Vercel's built-in web analytics for monitoring site performance and visitors.",
  "Visa": "Global payment technology company, detected via checkout or payment integrations.",
  "Web2py": "Full-stack Python web framework with a built-in web-based IDE.",
  "Weglot": "Website translation service providing multilingual content through a simple integration.",
  "XAMPP": "Free cross-platform web server bundle including Apache, MariaDB, PHP, and Perl.",
  "XOOPS": "Open-source PHP CMS and web portal system with a modular architecture.",
  "Zen Cart": "Open-source PHP ecommerce shopping cart derived from osCommerce.",
  "Zend": "Professional PHP framework for building enterprise web applications (now Laminas).",
  "Zepto": "Minimalist JavaScript library with a jQuery-compatible API for modern browsers.",
  "Zimbra": "Collaborative email and calendar suite for enterprise messaging.",
  "Zipkin": "Distributed tracing system for gathering timing data across microservices.",
  "Zone.js": "Library that patches async APIs to enable Angular's change detection.",
  "Zope": "Python-based open-source web application server and framework.",
  "eZ Publish": "Enterprise PHP CMS and digital experience platform, now Ibexa DXP.",
  "git": "Distributed version control system, detected via exposed repository metadata.",
  "gunicorn": "Python WSGI HTTP server for running Python web applications in production.",
  "osTicket": "Open-source support ticket system for managing customer inquiries.",
  "ownCloud": "Open-source file sync and share platform for self-hosted cloud storage.",
  "parcel": "Zero-configuration web application bundler for JavaScript projects.",
  "prettyPhoto": "jQuery lightbox plugin for displaying images, videos, and content overlays.",
  "script.aculo.us": "JavaScript UI effects and controls library built on Prototype.js.",
  "scrollreveal": "JavaScript library for animating elements as they scroll into view.",
  "total.js": "Full-featured Node.js framework for building web applications and REST APIs.",
  "Adminer": "Lightweight PHP database management tool, a single-file alternative to phpMyAdmin.",
  "Bugzilla": "Open-source web-based bug tracking system from Mozilla.",
  "Gerrit": "Web-based code review tool built on Git for collaborative software development.",
  "Loja Integrada": "Brazilian ecommerce platform for creating and managing online stores.",
  "Wix eCommerce": "Online store features built into the Wix website building platform.",
  "CMS Made Simple": "Open-source PHP CMS designed for simple, manageable website content.",
  "Serendipity": "PHP-powered blog and CMS engine with a flexible plugin architecture.",
  "Textpattern CMS": "Elegant open-source CMS built on PHP and MySQL for clean web publishing.",
  "Wolf CMS": "Lightweight open-source CMS built on PHP, inspired by Radiant CMS.",
  "papaya CMS": "Open-source PHP CMS for managing multilingual enterprise web content.",
  "Acquia Cloud Platform CDN": "CDN service integrated with Acquia's Drupal cloud hosting platform.",
  "Azion": "Edge computing platform with CDN, serverless, and security services.",
  "Bloomreach": "Digital experience platform combining CMS, search, and merchandising for commerce.",
  "Brightspot": "Enterprise Java CMS for publishers and media organizations.",
  "Business Catalyst": "Adobe's website builder and hosting platform for small businesses (discontinued).",
  "DERAK.CLOUD": "Iranian CDN and cloud security provider offering DDoS protection and acceleration.",
  "Fireblade": "Cloud-based web security and CDN platform for website protection.",
  "Flyspray": "Lightweight open-source web-based bug tracking system written in PHP.",
  "Indico": "Open-source event management and conference organization tool from CERN.",
  "Profitwell": "SaaS analytics platform for subscription revenue tracking and optimization.",
  "Splitbee": "Privacy-friendly web analytics and A/B testing tool (now part of Vercel).",
  "Svbtle": "Minimalist blogging platform focused on clean writing and reading.",
  "Webtrends": "Enterprise digital analytics platform for measuring web and mobile performance.",
  "Woopra": "Real-time customer analytics platform for tracking user journeys across touchpoints.",
  "CookieHub": "Cookie consent management platform for GDPR and ePrivacy compliance.",
  "CookieYes": "Cookie consent solution for GDPR, CCPA, and other privacy regulation compliance.",
  "Uniconsent": "Consent management platform for GDPR and CCPA cookie compliance.",
  "Google My Business": "Google's platform for managing business listings across Google Search and Maps.",
  "Zabbix": "Open-source enterprise monitoring platform for networks, servers, and applications."
};
